### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by jongbonga** [Kommunicate-io/Kommunicate-Capacitor-Plugin#10]
![Screenshot 2022-09-27 at 18 44 09](https://user-images.githubusercontent.com/12111716/192586438-a2b1dbc2-5ebf-4239-91f6-fabdcbcdcd29.png)

**Comment by amntoppo** [comment]
@jongbonga We are aware of this issue and we are working on this. It will be finished by end of Quarter 4.
Also, this only comes up as a warning, you will still be able to publish the app.
