### ISSUE TITLE
Kingfisher Version Issue

### ISSUE THREAD

**Issue by ayehia** [Kommunicate-io/Kommunicate-Capacitor-Plugin#11]
We faced an [issue](https://github.com/onevcat/Kingfisher/pull/2029) with Kingfisher (~> 7.0.0) XCode v14.3

This was fixed in Kingfisher (~> 7.6.0), we updated our app to use this version, but now we can not use your plugin due to the following error:
![image](https://user-images.githubusercontent.com/12626365/229517608-3b9b9c3a-b402-4b6f-ab25-2b22a56139e8.png)

Can you upgrade your plugin to use Kingfisher (~> 7.6.0) ?

**Comment by Sathyan-KM** [comment]
Hi @ayehia  Thanks for reporting this. Will fix this in upcoming release which scheduled on next week.Thanks

**Comment by Sathyan-KM** [comment]
@ayehia Since its the blocker for your development, Will fix & release it ASAP. Thanks

**Comment by ayehia** [comment]
> @ayehia Since its the blocker for your development, Will fix & release it ASAP. Thanks↳

Thank you so much, Appreciated!

**Comment by ayehia** [comment]
@Sathyan-KM 
Could you please let us know when exactly you can make this done as our development team is blocked.

**Comment by Sathyan-KM** [comment]
@ayehia Fix will be released by tomorrow.

**Comment by ayehia** [comment]
> @ayehia We have released new version(2.5.0) which contains fix for it.↳

Thank you! Fixed now.

**Comment by Sathyan-KM** [comment]
@ayehia Thanks for the update. Closing this issue.
