### ISSUE TITLE
Update latest pods

### ISSUE THREAD

**Issue by jongbonga** [Kommunicate-io/Kommunicate-Capacitor-Plugin#15]
The current version of the plugin locks the pod to an older version
<img width="462" alt="Screenshot 2023-09-27 at 12 07 08" src="https://github.com/Kommunicate-io/Kommunicate-Capacitor-Plugin/assets/12111716/b3f1ef6f-8d8c-45e8-87bb-bfc65a9d382e">
This causes the iOS build to fail on `Xcode 15`
<img width="265" alt="Screenshot 2023-09-27 at 12 08 57" src="https://github.com/Kommunicate-io/Kommunicate-Capacitor-Plugin/assets/12111716/0a9a4ad8-4e77-49aa-b263-0a32d5676dc7">

**Comment by jongbonga** [comment]
Hi @AbhijeetRanjan308 any updates on this? We are blocked from pushing new builds because of this issue

**Comment by AbhijeetRanjan308** [comment]
Hi @jongbonga , thank you for your message. We are actively addressing this issue and are planning to proceed with the new release next week. I'll be sure to keep you updated after the release.

**Comment by jongbonga** [comment]
Hello @AbhijeetRanjan308 is there any progress on this matter? my team is being pressured to release the app but we cannot build it because of this.

**Comment by AbhijeetRanjan308** [comment]
Hello @jongbonga , I'm pleased to share some great news with you – our latest release, version 3.0.0, solves the Xcode 15 issue.

**Comment by jongbonga** [comment]
> Hello @jongbonga , I'm pleased to share some great news with you – our latest release, version 3.0.0, solves the Xcode 15 issue.

Sounds Great, when will it be available for download?

**Comment by jongbonga** [comment]
> Hello @jongbonga , I'm pleased to share some great news with you – our latest release, version 3.0.0, solves the Xcode 15 issue.

Amazing stuff, thank you
