### ISSUE TITLE
Capacitor 3 support

### ISSUE THREAD

**Issue by jongbonga** [Kommunicate-io/Kommunicate-Capacitor-Plugin#6]
<img width="619" alt="Screenshot 2022-07-01 at 11 22 41" src="https://user-images.githubusercontent.com/12111716/176866479-ec781ed9-ad03-410a-a7cd-7022812590d8.png">

<img width="1189" alt="Screenshot 2022-07-01 at 12 37 17" src="https://user-images.githubusercontent.com/12111716/176878952-b5bae5d7-c68b-4f55-91df-6f1dc5502d31.png">

**Comment by sonujangra27** [comment]
Capacitor 3 is not yet supported, we will add it to our roadmap.
Alternatively, you can use our Web SDK code. It will work perfectly with Capacitor 3.

Please check the link for reference:https://docs.kommunicate.io/docs/web-installation

**Comment by jongbonga** [comment]
can I use the Cordova plugin with Capacitor instead? 
I tried and worked on iOS but not Android

**Comment by amntoppo** [comment]
Cordova Plugin might work with Capacitor but we do not actively support using Cordova Plugin in Capacitor. 
Release with Capacitor 3 support is scheduled on 22nd July.
