### ISSUE TITLE
Error while running KommunicateCapacitorPlugin.buildConversation() on Android

### ISSUE THREAD

**Issue by cyrilfr** [Kommunicate-io/Kommunicate-Capacitor-Plugin#9]
I was able to run the plugin on Android a few weeks ago but now when I try to run `KommunicateCapacitorPlugin.buildConversation()`, I get an error in my Google Chrome console:

```
account-home.page.ts:187 Error: Some internal error occurred
    at cap.fromNative (VM3:414:32)
    at <anonymous>:1:18
(anonymous) @ account-home.page.ts:187
rejected @ tslib.es6.js:74
push.23484._ZoneDelegate.invoke @ zone.js:409
onInvoke @ core.mjs:25548
push.23484._ZoneDelegate.invoke @ zone.js:408
push.23484.Zone.run @ zone.js:169
(anonymous) @ zone.js:1326
push.23484._ZoneDelegate.invokeTask @ zone.js:443
onInvokeTask @ core.mjs:25535
push.23484._ZoneDelegate.invokeTask @ zone.js:442
push.23484.Zone.runTask @ zone.js:214
drainMicroTaskQueue @ zone.js:632
Promise.then (async)
nativeScheduleMicroTask @ zone.js:608
scheduleMicroTask @ zone.js:619
push.23484._ZoneDelegate.scheduleTask @ zone.js:433
onScheduleTask @ zone.js:320
push.23484._ZoneDelegate.scheduleTask @ zone.js:423
push.23484.Zone.scheduleTask @ zone.js:257
push.23484.Zone.scheduleMicroTask @ zone.js:277
scheduleResolveOrReject @ zone.js:1316
resolvePromise @ zone.js:1253
(anonymous) @ zone.js:1169
(anonymous) @ zone.js:1185
cap.fromNative @ VM3:431
(anonymous) @ VM775:1
```

I'm using capacitor 3.7 and the last version of the plugin.

Here is the code I tried:

    const kmUser = {
      userId: this.me.accountNumber,
      displayName: this.me.contact.firstName,
      email: this.me.contact.email,
      contactNumber: this.me.contact.mobile
    };
    const conversationObject = {
      appId: 'fdbf99df07eb6b0618aae16a23311ea1',
      kmUser: JSON.stringify(kmUser)
    };
    try {
      await KommunicateCapacitorPlugin.buildConversation(conversationObject);
    } catch (err) {
      console.error(err);
    }

**Comment by amntoppo** [comment]
Please update to latest version, if you have not already.
Are you able to run on Android or iOS?

**Comment by cyrilfr** [comment]
I did a new fresh install and now it works! Sorry for the inconvenience.
